(((lua-ts-mode pico8-mode)
  (indent-tabs-mode . t)
  (line-spacing . 4)
  (tab-width . 1)
  (lua-ts-indent-offset . 1)
  (lua-indent-level . 1)
  (eval
   (lambda ()
     (mauzy/downcase-only-mode)
     ;; (auto-fill-mode)
     ;; (set-fill-column 40)
     (face-remap-add-relative 'default '(:family "PICO-8" :weight regular :height 200))))))
